import { Router } from "express";
import {
  createDueRequest,
  getDueRequestsForApprover,
  approveDueRequest,
  createFranchiseDueRequest,
  getDueRequestStatistics,
  getFranchisePendingBills,
  getDueRequestById,
  getAdminAutoGeneratedBills,
  getFranchiseDueRequestHistory,
  getFranchiseBillingDashboard,
} from "../controllers/dueRequest.controller.js";

const router = Router();

// ============================================
// DRIVER ROUTES
// ============================================

// Driver creates due request (public endpoint for drivers)
router.route("/driver").post(createDueRequest);

// ============================================
// ADMIN & FRANCHISE ROUTES
// ============================================

// Get due requests based on user role (query params required)
router.route("/").get(getDueRequestsForApprover);

// Get statistics
router.route("/statistics").get(getDueRequestStatistics);

// ============================================
// FRANCHISE SPECIFIC ROUTES (Auto-generated bills)
// ============================================

// Franchise  pending auto-generated bills (for manual due request creation)
router
  .route("/franchise/:franchiseId/pending-bills")
  .get(getFranchisePendingBills);

// Franchise manually creates due request from auto-generated bill
router
  .route("/franchise/:franchiseId/create-from-bill")
  .post(createFranchiseDueRequest);

router
  .route("/franchise/:franchiseId/history")
  .get(getFranchiseDueRequestHistory);
router
  .route("/franchise/:franchiseId/dashboard")
  .get(getFranchiseBillingDashboard);

// Approve due request
router.route("/:dueRequestId/approve").patch(approveDueRequest);

// Get single due request by ID
router.route("/:id").get(getDueRequestById);

//
router.route("/admin/auto-bills").get(getAdminAutoGeneratedBills);

export default router;
