import mongoose, { Schema } from "mongoose";

const weeklyBillSchema = new Schema(
  {
    franchiseId: {
      type: Schema.Types.ObjectId,
      ref: "Franchise",
      required: true,
    },

    adminId: {
      type: Schema.Types.ObjectId,
      ref: "Admin",
      required: true,
    },

    weekStartDate: {
      type: Date,
      required: true,
    },

    weekEndDate: {
      type: Date,
      required: true,
    },

    totalGeneratedAmount: {
      type: Number,
      default: 0,
    },

    adminCommissionAmount: {
      type: Number,
      default: 0,
    },

    franchiseCommissionAmount: {
      type: Number,
      default: 0,
    },

    dueAmount: {
      type: Number,
      default: 0,
    },

    status: {
      type: String,
      enum: ["generated", "pending_payment", "paid", "cancelled"],
      default: "generated",
    },

    isAutoGenerated: {
      type: Boolean,
      default: true,
    },

    dueRequestId: {
      type: Schema.Types.ObjectId,
      ref: "DueRequest",
      default: null,
    },

    dueRequestCreated: {
      type: Boolean,
      default: false,
    },

    dueRequestCreatedAt: {
      type: Date,
      default: null,
    },

    paymentDetails: {
      paymentMethod: {
        type: String,
        enum: ["cash", "online"],
      },
      paymentPhoto: {
        type: String,
      },
      paidAmount: {
        type: Number,
        default: 0,
      },
      paymentDate: {
        type: Date,
      },
    },

    notes: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes
weeklyBillSchema.index({ franchiseId: 1, status: 1 });
weeklyBillSchema.index({ weekStartDate: 1, weekEndDate: 1 });
weeklyBillSchema.index({ createdAt: -1 });

export const WeeklyBill = mongoose.model("WeeklyBill", weeklyBillSchema);
